# docker-compose.filebeat.yml
# 기본 Filebeat 설정 - 환경별 오버라이드 파일과 함께 사용
# 로컬: docker-compose -f docker-compose.filebeat.yml -f docker-compose.filebeat.local.yml up -d
# 서버: docker-compose -f docker-compose.filebeat.yml -f docker-compose.filebeat.server.yml up -d

services:
  filebeat-agent:
    image: docker.elastic.co/beats/filebeat:8.14.1
    container_name: asyncsite-filebeat-agent
    restart: unless-stopped
    user: root
    networks:
      - asyncsite-network
    volumes:
      - /var/log/containers:/var/log/host_logs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro


networks:
  asyncsite-network:
    external: true