filebeat.inputs:
  - type: log
    enabled: true
    paths:
      # 마운트된 디렉터리 아래의 모든 로그 파일을 대상으로 함
      - /var/log/host_logs/*/*.log
    # JSON 로그 파싱 활성화
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true
    json.message_key: message

# Docker 메타데이터를 자동으로 추가하여 어떤 컨테이너의 로그인지 식별
processors:
  - add_docker_metadata: ~

# Elasticsearch 직접 연결 비활성화
setup.template.enabled: false
setup.ilm.enabled: false

output.logstash:
  hosts: ["logstash:5044"]