# filebeat-server.yml
# 서버 환경용 Filebeat 설정 - Docker 컨테이너 로그 직접 수집
filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    # AsyncSite 애플리케이션 서비스만 포함
    include_lines: ['user-service', 'gateway', 'eureka-server', 'study-service', 'game-service', 'noti-service', 'notion-automation']
    # 인프라 서비스 제외
    exclude_lines: ['mysql', 'redis', 'elasticsearch', 'kibana', 'logstash', 'filebeat']
    
    # Docker JSON 파싱 설정
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true
    json.message_key: log
    
    processors:
      # 1. Docker 메타데이터 추가
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      
      # 2. log 필드가 JSON 문자열인 경우 파싱
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 1
          target: ""
          overwrite_keys: true
          add_error_key: true

# 추가 프로세서 - 모든 입력에 적용
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded

# Elasticsearch 직접 연결 비활성화
setup.template.enabled: false
setup.ilm.enabled: false

# Logstash로 출력
output.logstash:
  hosts: ["logstash:5044"]

# 로깅 설정
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644