name: Deploy ELK Stack to Mini PC

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 배포할 코드(설정 파일 포함)를 GitHub Actions 러너 환경으로 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 러너에 있는 설정 파일들을 원격 Mini PC로 복사합니다.
      - name: Copy config files to Mini PC
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MINI_PC_HOST }}
          username: ${{ secrets.MINI_PC_USER }}
          key: ${{ secrets.MINI_PC_SSH_KEY }}
          port: 2222
          source: | # 복사할 파일 및 디렉터리 목록
            ./docker-compose.yml
            ./docker-compose.filebeat.yml
            ./docker-compose.filebeat.server.yml
            ./filebeat.yml
            ./logstash/
          target: "~/elk-stack"
          rm: true # 복사 전 원격 디렉터리 내용 삭제

      # 3. Mini PC에 접속하여 Docker Compose를 실행합니다.
      - name: Execute docker-compose on Mini PC
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MINI_PC_HOST }}
          username: ${{ secrets.MINI_PC_USER }}
          key: ${{ secrets.MINI_PC_SSH_KEY }}
          port: 2222
          script: |
            cd ~/elk-stack
            # 파일 소유자 변경
            sudo chown root:root ./filebeat.yml
            # 스택 실행
            docker compose pull
            docker-compose -f docker-compose.filebeat.yml -f docker-compose.filebeat.server.yml up -d