# .github/workflows/deploy-to-minipc.yml

name: Deploy to Mini PC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 배포할 코드(현재 브랜치)를 GitHub Actions 러너 환경으로 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 러너에 있는 프로젝트 파일 전체를 원격 Mini PC로 복사합니다.
      # rsync 또는 scp를 사용하며, scp-action을 사용하면 편리합니다.
      - name: Copy files to Mini PC via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MINI_PC_HOST }}
          username: ${{ secrets.MINI_PC_USER }}
          key: ${{ secrets.MINI_PC_SSH_KEY }}
          source: "./*" # 현재 디렉터리의 모든 파일을
          target: "~/elk-stack" # 원격 서버의 작업 디렉터리로 복사
          rm: true # 복사하기 전, 원격 디렉터리의 기존 파일을 모두 삭제 (선택 사항)

      # 3. Mini PC에 접속하여 Docker Compose를 실행합니다.
      - name: Execute docker-compose on Mini PC
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MINI_PC_HOST }}
          username: ${{ secrets.MINI_PC_USER }}
          key: ${{ secrets.MINI_PC_SSH_KEY }}
          script: |
            cd ~/elk-stack
            docker-compose down
            docker-compose up --build -d