# .github/workflows/deploy-to-minipc.yml

name: Deploy to Mini PC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to Mini PC via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MINI_PC_HOST }}
          username: ${{ secrets.MINI_PC_USER }}
          key: ${{ secrets.MINI_PC_SSH_KEY }}
          port: 2222 # <-- 이 라인이 누락되었습니다.
          source: "./*"
          target: "~/elk-stack"
          rm: true

      - name: Execute docker-compose on Mini PC
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MINI_PC_HOST }}
          username: ${{ secrets.MINI_PC_USER }}
          key: ${{ secrets.MINI_PC_SSH_KEY }}
          port: 2222
          script: |
            cd ~/elk-stack
            docker compose down
            docker compose up --build -d